#!/usr/bin/bash

echo "Start Visual Studio Code server"
code-server \
    --bind-addr 0.0.0.0:8081 \
    --auth none \
    --proxy-domain vscode \
    --user-data-dir ~/ \
    --extensions-dir /tmp/codeserver-extensions \
    --disable-update-check \
    --disable-telemetry \
    &

sleep infinity
